// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uxgylxdhaembwlawsiwf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV4Z3lseGRoYWVtYndsYXdzaXdmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NDg1NzAsImV4cCI6MjA2NzUyNDU3MH0.BbNzKh3tmZGuFCYH3kOoymjDHqgKlmogoP_E1U1X0KY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});